version: '2.1'
services:
  mysql-server:
    container_name: mysql-server
    image: 'mysql:8.0.23'
    volumes:
      - mysql-server-db:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
  boot-api-app:
    image: boot-api-app
    build:
      context: ./boot-api-app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      MYSQL_SERVER_HOST: mysql-server
    depends_on:
      mysql-server:
        condition: service_healthy

volumes: 
    mysql-server-db:
      external: true
